language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
install: pip install -r requirements.txt
script: nosetests
cache:
  directories:
  - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages
  - /home/travis/virtualenv/python3.2/lib/python3.2/site-packages
  - /home/travis/virtualenv/python3.3/lib/python3.3/site-packages
  - /home/travis/virtualenv/python3.4/lib/python3.4/site-packages
